### ISSUE TITLE
Error while using in Nifi

### ISSUE THREAD

**Issue by harjitdotsingh** [geomesa/geomesa-nifi#65]
I compiled the master branch and installed on the Nifi Server version 1.8.0. I get this error when using the PutGeoMesaHbase Processor,

020-01-06 18:23:03,149 ERROR [Timer-Driven Process Thread-1] o.g.n.p.datastore.PutGeoMesaHBase PutGeoMesaHBase[id=7c08ec2a-016f-1000-0000-000029710344] Failed to properly initialize Processor. If still scheduled to run, NiFi will attempt to initialize and run the Processor again after the 'Administrative Yield Duration' has elapsed. Failure is due to java.lang.reflect.InvocationTargetException: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotations(ReflectionUtils.java:142)
	at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotations(ReflectionUtils.java:130)
	at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotations(ReflectionUtils.java:75)
	at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotation(ReflectionUtils.java:52)
	at org.apache.nifi.controller.StandardProcessorNode.lambda$initiateStart$4(StandardProcessorNode.java:1504)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2860)
	at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2706)
	at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2579)
	at org.apache.hadoop.conf.Configuration.get(Configuration.java:1091)
	at org.locationtech.geomesa.hbase.data.HBaseConnectionPool$$anon$1.load(HBaseConnectionPool.scala:51)
	at org.locationtech.geomesa.hbase.data.HBaseConnectionPool$$anon$1.load(HBaseConnectionPool.scala:35)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache$UnboundedLocalLoadingCache.lambda$new$0(UnboundedLocalCache.java:922)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.lambda$computeIfAbsent$2(UnboundedLocalCache.java:235)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.computeIfAbsent(UnboundedLocalCache.java:231)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:65)
	at org.locationtech.geomesa.hbase.data.HBaseConnectionPool$.getConfiguration(HBaseConnectionPool.scala:87)
	at org.locationtech.geomesa.hbase.data.HBaseConnectionPool$.getConnection(HBaseConnectionPool.scala:101)
	at org.locationtech.geomesa.hbase.data.HBaseDataStoreFactory.createDataStore(HBaseDataStoreFactory.scala:41)
	at org.locationtech.geomesa.hbase.data.HBaseDataStoreFactory.createDataStore(HBaseDataStoreFactory.scala:31)
	at org.geotools.data.DataAccessFinder.getDataStore(DataAccessFinder.java:119)
	at org.geotools.data.DataStoreFinder.getDataStore(DataStoreFinder.java:69)
	at org.geomesa.nifi.processors.AbstractGeoIngestProcessor.initialize(AbstractGeoIngestProcessor.scala:108)
	... 15 common frames omitted
Caused by: org.xml.sax.SAXParseException: Content is not allowed in prolog.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
	at org.apache.hadoop.conf.Configuration.parse(Configuration.java:2684)
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2760)

**Comment by elahrvivaz** [comment]
This is caused by having an hbase-site.xml or another configuration file that has invalid XML.
